print('###############')
print()
print("笑         飞")
print("书         雪")
print("神         连")
print("侠         天")
print("倚         射")
print("碧         白")
print("鸳         鹭")
print()
print('###############')
